version: '3.8'

services:
  web:
    image: nginx
    ports:
      - 80:80
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
  app:
    image: wordpress
    depends_on:
      - db
    ports:
      - 5000:5000