# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtenemos codigo fuente
      - checkout
      # Step 2: creamos venv e instalamos dependencias
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      # Step 3: ejecutamos linters y flake8 y lanzamos casos de prueba
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v
#      - setup_remote_docker:
#          docker_layer_caching: true
      # Step 4: Docker build
      - run:
          name: Build and Push Docker
          command: |
            source venv/bin/activate
            #docker build -t poc/$IMAGE_NAME:$TAG .
            #echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            #docker push ideaslocas/$IMAGE_NAME:$TAG
      # Step 5: pre-cache dependencies
      - run:
          name: pre-cache dependencies
          command: |
            source venv/bin/activate
            pip download -r requirements.txt
      # Step 6: post-cache dependencies
      - run:
          name: post-cache dependencies
          command: |
            source venv/bin/activate
            pip cache publish
      # Step 7: run coverage tests
      - run:
          name: run coverage tests
          command: |
            source venv/bin/activate
            pytest --cov=app --cov-report=html