# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtenemos codigo fuente
      - checkout
      # Step 2: creamos venv e instalamos dependencias
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install flake8 --upgrade
            pip install -r requirements.txt
            pip install pytest-integration
      # Step 3: ejecutamos linters y flake8 y lanzamos casos de prueba
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v
      # Step 4: run integration tests
      - run:
          name: run integration tests
          command: |
            source venv/bin/activate
            pytest -v --integration
      # Step 5: run performance tests
      - run:
          name: run performance tests
          command: |
            source venv/bin/activate
            locust -f locustfile.py
      # Step 6: coverage report
      - run:
          name: coverage report
          command: |
            source venv/bin/activate
            pytest --cov=app --cov-report=html            
#      - setup_remote_docker:
#          docker_layer_caching: true
      # Step 4: Docker build
      - run:
          name: Build and Push Docker
          command: |
            source venv/bin/activate
            #docker build -t poc/$IMAGE_NAME:$TAG .
            #echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            #docker push ideaslocas/$IMAGE_NAME:$TAG
