name: CI/CD

on:
  push:
    branches:
      - feature/new

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Current Dir
        run: pwd

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install bandit
        run: pip install bandit

      - name: Install nose
        run: pip install nose

      - name: Run static code analysis
        run: bandit -r app

      - name: Run integration tests
        run: nosetests

      - name: Run tests
        run: pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t app .

      - name: Push Docker image
        run: docker push app -p ${{ secrets.TOKEN }}
